### ISSUE TITLE
Ability to Add Email + Attachments

### ISSUE THREAD

**Issue by rvalente** [mailmate/devonthink-pro.mmbundle#1]
I would like to have the ability to add the email to DEVONthink as well as a separate attachment file, that way I can go in and cleanup all attachments from all emails. Very handle, because just a pointer to the attachment ends up breaking if you delete the original email.

**Comment by freron** [comment]
I don't think I quite understand what you want to do. The DEVONThink 
bundle allows you to archive the entire email (_including its 
attachments_) into DEVONThink. The pointer (URL link) is just to open 
the original email in MailMate. What is it you want to be able to do?

**Comment by rvalente** [comment]
Ideally what I would like is the email content `.eml` to be sent to DEVONthink Global Inbox and label as `${subject.blob}`, additionally I would like the attachment to be sent to the DEVONthink Global Inbox as well, named whatever its called, and tagged with `${subject.blob}` and `attachment`. That would be a pretty sweet workflow, because then you could A) still be able to respond to the email by double clicking and opening in MailMate.app, and B) delete the email completely from MailMate.app or at least the attachment from the email.

People I work with have a tendency of emailing around > 10MB attachments so storing all that in MailMate (or any lesser email client) is quite painful.
