### ISSUE TITLE
Message in DEVONthink does not have the expected Modified- date

### ISSUE THREAD

**Issue by halloleo** [mailmate/devonthink-pro.mmbundle#5]
When adding a message to DEVONthink the _Modfied_-date is set to the current date (as is the _Added_-date). 

That is quite unexpected though; IMHO the last modification should rather reflect the date when the email was stored in the mail box. This date is saved in DEVONthink in the _Created_-date.

Furthermore DEVONthink's  "Add from Apple Mail" script sets the _Modfied_-date and _Created_-date together.

**Comment by halloleo** [comment]
To illustrate the issue a bit more here a screenshot cut out from DEVONthink's viewer pane showing the same email once imported from Apple Mail and once imported via MailMate's `devonthink-pro` bundle:

![Message import from Apple Mail and Mailmate (Screen shot)](https://user-images.githubusercontent.com/1521852/50723015-14666980-112c-11e9-91cb-cae90d8521c9.png)

Note the values in the _Modified_ column.

**Comment by freron** [comment]
Fixed by @halloleo. Sorry about the delay.
